	[machine.general]
		#The data component types that should be filtered away when checking equality.
		ignoreDataComponentsForEqualityFilters = []

	[core.general]
		#Only enable this if you know what you are doing, as this will cause lag! This will log checks to the DataComparator where equal items have unequal data components.
		debugLogUnequalItemDataComponents = false
