#List of groups to disable. Has precedence over includedGroups. 'selling.seeds' for example would disable all seeds from the market.
excludedGroups = []
#The range within animals can be fed by the feeding trough.
feedingTroughRange = 8
#The chance for Fertilized Farmland to turn back into regular Farmland (per provided bonus).
fertilizerRegressionChance = 0.0
#If true, merchants will be considered babies (on a technical level only), which may resolve exploits based on merchant death loot (like blood)
treatMerchantsLikeBabies = true
#The chance to get a bonus growth when using Red Fertilizer.
fertilizerBonusGrowthChance = 1.0
#List of names the merchant can have.
merchantNames = [
  "Der Heuknecht",
  "Der Feldfuchs",
  "Der Wurzelweiser",
  "Der Saatmeister",
  "Der Krautkönig",
  "Der Mistmagus",
  "Der Düngerdrache",
  "Der Ackergeist",
  "Der Kornkobold",
  "Der Rankenschurke",
  "Der Kürbisknecht",
  "Der Apfelalchimist",
  "Der Rübenritter",
  "Der Kartoffelbaron",
  "Der Beerenbarde",
  "Der Stallknecht",
  "Der Pflugpriester",
  "Der Schafschelm",
  "Der Erntegreis",
  "Der Halmhändler",
  "Der Gemüsegaukler",
  "Der Hühnerfürst",
  "Der Weizenzauberer",
  "Der Krautkrämer",
  "Der Milchknecht",
  "Der Butterbursche",
  "Der Honighehler",
  "Der Brotbanause",
  "Der Marktmäster",
  "Der Kornkönig",
  "Der Wiesenwicht",
  "Der Strohschurke",
  "Der Ziegenzauberer",
  "Der Mistwicht",
  "Der Säemönch",
  "Der Rebenhüter",
  "Der Beutelbauer",
  "Der Traktortrunkenbold",
  "Der Heuhändler",
  "Der Kräuterkauz",
  "Der Gemüsegreis",
  "Der Saatzauberer",
  "Der Wucherwirt",
  "Der Ackeralchimist",
  "Der Pfennigpflüger",
  "Der Erbsenzähler",
  "Der Dungdiplomat",
  "Der Stallbaron",
  "Der Futterfex",
  "Der Hülsenhändler",
  "Der Marktmaulige",
  "Der Pflanzpächter",
  "Der Ernteschalk",
  "Der Schweinemeister",
  "Der Viehvikar",
  "Der Hühnerheini",
  "Der Kleepriester",
  "Der Lauchlord",
  "Der Kornkleriker",
  "Der Krämerknecht",
  "Der Mistmönch",
  "Der Pflanzpanscher",
  "Der Saatzauberbursche",
  "Der Futterfürst",
  "Der Weidenwichtel",
  "Der Knollenkobold",
  "Der Melkmeister",
  "Der Feldknecht",
  "Der Ackerbarde",
  "Der Hofhehler",
  "Der Gurkengeist",
  "Der Kornschurke",
  "Der Krautknecht",
  "Der Schafschurmagus",
  "Der Rübenrammler",
  "Der Saatsetzer",
  "Der Wiesenweiser",
  "Der Dungdrache",
  "Der Viehverschmitzte",
  "Der Karrenkrämer",
  "Der Halmhüter",
  "Der Bauernbaron",
  "Der Heuhaufenhändler",
  "Der Saatling",
  "Der Erntehans",
  "Der Stallstratege",
  "Der Pflanzpöbel",
  "Der Mistmogul",
  "Der Feldfratz",
  "Der Kornknecht",
  "Der Kartoffelkrämer",
  "Der Pflugpate",
  "Der Ackeradlige",
  "Der Gemüsejunkie",
  "Der Beerenbaron",
  "Der Strohmeister",
  "Der Tränketräger",
  "Der Hühnerhofnarr",
  "Der Wiesenwaidler",
  "Der Pflanzpatron",
  "Der Feldfex",
  "Der Saatknecht"
]
#List of groups to enable. 'default' is an alias for the inbuilt defaults (selling.seeds, selling.saplings and selling.fertilizers.minecraft).
includedGroups = ["default"]
#The range at which the chicken nest picks up laid eggs.
chickenNestRange = 8
#The maximum amount of animals (per type) until the feeding trough stops feeding.
feedingTroughMaxAnimals = 24
#The chance to get a bonus crop when using Green Fertilizer.
fertilizerBonusCropChance = 1.0
